spring :
  profiles:
    active: dev
  application:
    name: doors-usermanagement
  datasource:
    url: jdbc:mariadb://localhost:3306/doors
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:h2:mem:mydb1
#    username:
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 5001

eureka:
    client:
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
